# All values in no of frames
MATRIX_SIZE: 5
DISTRACTOR_NUM: 15
DISTRACTOR_SIZE: 60
DISTRACTOR_COLOR: orange
TARGET_SIZE: 60
TARGET_COLOR: red
TARGET_PROBABILITY: 64
STIM_TIME: 100
BACKGROUND_COLOR: white
FRAME_RATE: 60
FIX_CROSS_TIME: 48
TRAINING_SESSIONS: 10
EXPERIMENT_SESSIONS: 50
NO_BLOCKS: 2
FIX_CROSS_COLOR: black
REACTION_KEYS: [space]

